---
name: "RandomSpawn"
author: "Sandertv"
api: [3.0.0]
main: Sandertv\RandomSpawn\RandomSpawn
version: 1.0

commands:
  randomspawnposition:
    usage: "/randomspawnposition <ID>"
    permission: "randomspawn.setposition"
    aliases: ["rsp", "randomspawnpos", "rspawnpos", "randomsp", "randomspawn", "rssetpos", "randomspawnsetpos"]
    description: "Set or modify one of the random spawn positions"
permissions:
  randomspawn.setposition:
    default: op
    description: "Allows access to the randomspawnposition command"
...
